// File generated by attrgen

#pragma warning disable 1591

namespace CursesSharp
{
	// Character attributes
	public static class Attrs
	{
		public const uint NORMAL = 0x00000000U;
		public const uint ALTCHARSET = 0x00400000U;
		public const uint BLINK = 0x00080000U;
		public const uint BOLD = 0x00200000U;
		public const uint DIM = 0x00100000U;
		public const uint INVIS = 0x00800000U;
		public const uint PROTECT = 0x01000000U;
		public const uint REVERSE = 0x00040000U;
		public const uint STANDOUT = 0x00010000U;
		public const uint UNDERLINE = 0x00020000U;
		// Attribute masks
		public const uint ATTRIBUTES = 0xffffff00U;
		public const uint CHARTEXT = 0x000000ffU;
		public const uint COLOR = 0x0000ff00U;
	}

	// Line drawing characters
	public static class Acs
	{
		public const uint BLOCK = 0x00400030U;
		public const uint BOARD = 0x00400068U;
		public const uint BTEE = 0x00400076U;
		public const uint BULLET = 0x0040007eU;
		public const uint CKBOARD = 0x00400061U;
		public const uint DARROW = 0x0040002eU;
		public const uint DEGREE = 0x00400066U;
		public const uint DIAMOND = 0x00400060U;
		public const uint GEQUAL = 0x0040007aU;
		public const uint HLINE = 0x00400071U;
		public const uint LANTERN = 0x00400069U;
		public const uint LARROW = 0x0040002cU;
		public const uint LEQUAL = 0x00400079U;
		public const uint LLCORNER = 0x0040006dU;
		public const uint LRCORNER = 0x0040006aU;
		public const uint LTEE = 0x00400074U;
		public const uint NEQUAL = 0x0040007cU;
		public const uint PI = 0x0040007bU;
		public const uint PLMINUS = 0x00400067U;
		public const uint PLUS = 0x0040006eU;
		public const uint RARROW = 0x0040002bU;
		public const uint RTEE = 0x00400075U;
		public const uint S1 = 0x0040006fU;
		public const uint S3 = 0x00400070U;
		public const uint S7 = 0x00400072U;
		public const uint S9 = 0x00400073U;
		public const uint STERLING = 0x0040007dU;
		public const uint TTEE = 0x00400077U;
		public const uint UARROW = 0x0040002dU;
		public const uint ULCORNER = 0x0040006cU;
		public const uint URCORNER = 0x0040006bU;
		public const uint VLINE = 0x00400078U;
	}

	// Colors
	public static class Colors
	{
		public const short BLACK = 0x0;
		public const short BLUE = 0x4;
		public const short GREEN = 0x2;
		public const short CYAN = 0x6;
		public const short RED = 0x1;
		public const short MAGENTA = 0x5;
		public const short YELLOW = 0x3;
		public const short WHITE = 0x7;
	}

	// Keys
	public static class Keys
	{
		public const int ESC = 0x01B;
		public const int CTRLC = 0x003;
		public const int CTRLZ = 0x01A;
		public const int BREAK = 0x101;
		public const int DOWN = 0x102;
		public const int UP = 0x103;
		public const int LEFT = 0x104;
		public const int RIGHT = 0x105;
		public const int HOME = 0x106;
		public const int BACKSPACE = 0x107;
		public const int F0 = 0x108;
		public const int DL = 0x148;
		public const int IL = 0x149;
		public const int DC = 0x14a;
		public const int DELETEKEY = 0x14a;
		public const int IC = 0x14b;
		public const int INSERTKEY = 0x14b;
		public const int EIC = 0x14c;
		public const int CLEAR = 0x14d;
		public const int EOS = 0x14e;
		public const int EOL = 0x14f;
		public const int SF = 0x150;
		public const int SR = 0x151;
		public const int NPAGE = 0x152;
		public const int PPAGE = 0x153;
		public const int STAB = 0x154;
		public const int CTAB = 0x155;
		public const int CATAB = 0x156;
		public const int ENTER = 0x157;
		public const int SRESET = 0x158;
		public const int RESET = 0x159;
		public const int PRINT = 0x15a;
		public const int LL = 0x15b;
		public const int A1 = 0x15c;
		public const int A3 = 0x15d;
		public const int B2 = 0x15e;
		public const int C1 = 0x15f;
		public const int C3 = 0x160;
		public const int BTAB = 0x161;
		public const int BEG = 0x162;
		public const int CANCEL = 0x163;
		public const int CLOSE = 0x164;
		public const int COMMAND = 0x165;
		public const int COPY = 0x166;
		public const int CREATE = 0x167;
		public const int END = 0x168;
		public const int EXIT = 0x169;
		public const int FIND = 0x16a;
		public const int HELP = 0x16b;
		public const int MARK = 0x16c;
		public const int MESSAGE = 0x16d;
		public const int MOUSE = 0x199;
		public const int MOVE = 0x16e;
		public const int NEXT = 0x16f;
		public const int OPEN = 0x170;
		public const int OPTIONS = 0x171;
		public const int PREVIOUS = 0x172;
		public const int REDO = 0x173;
		public const int REFERENCE = 0x174;
		public const int REFRESH = 0x175;
		public const int REPLACE = 0x176;
		public const int RESIZE = 0x19a;
		public const int RESTART = 0x177;
		public const int RESUME = 0x178;
		public const int SAVE = 0x179;
		public const int SBEG = 0x17a;
		public const int SCANCEL = 0x17b;
		public const int SCOMMAND = 0x17c;
		public const int SCOPY = 0x17d;
		public const int SCREATE = 0x17e;
		public const int SDC = 0x17f;
		public const int SDL = 0x180;
		public const int SELECT = 0x181;
		public const int SEND = 0x182;
		public const int SEOL = 0x183;
		public const int SEXIT = 0x184;
		public const int SFIND = 0x185;
		public const int SHELP = 0x186;
		public const int SHOME = 0x187;
		public const int SIC = 0x188;
		public const int SLEFT = 0x189;
		public const int SMESSAGE = 0x18a;
		public const int SMOVE = 0x18b;
		public const int SNEXT = 0x18c;
		public const int SOPTIONS = 0x18d;
		public const int SPREVIOUS = 0x18e;
		public const int SPRINT = 0x18f;
		public const int SREDO = 0x190;
		public const int SREPLACE = 0x191;
		public const int SRIGHT = 0x192;
		public const int SRSUME = 0x193;
		public const int SSAVE = 0x194;
		public const int SSUSPEND = 0x195;
		public const int SUNDO = 0x196;
		public const int SUSPEND = 0x197;
		public const int UNDO = 0x198;

		public static int KEY_F(int n)
		{
			return Keys.F0 + n;
		}

		public const int MIN = 0x101;
		public const int MAX = 0x1ff;
	}

	// Mouse event masks
	[System.FlagsAttribute]
	public enum MouseState : uint
	{
		BUTTON1_PRESSED = 0x00000002U,
		BUTTON1_RELEASED = 0x00000001U,
		BUTTON1_CLICKED = 0x00000004U,
		BUTTON1_DOUBLE_CLICKED = 0x00000008U,
		BUTTON1_TRIPLE_CLICKED = 0x00000010U,
		BUTTON2_PRESSED = 0x00000080U,
		BUTTON2_RELEASED = 0x00000040U,
		BUTTON2_CLICKED = 0x00000100U,
		BUTTON2_DOUBLE_CLICKED = 0x00000200U,
		BUTTON2_TRIPLE_CLICKED = 0x00000400U,
		BUTTON3_PRESSED = 0x00002000U,
		BUTTON3_RELEASED = 0x00001000U,
		BUTTON3_CLICKED = 0x00004000U,
		BUTTON3_DOUBLE_CLICKED = 0x00008000U,
		BUTTON3_TRIPLE_CLICKED = 0x00010000U,
		BUTTON4_PRESSED = 0x00080000U,
		BUTTON4_RELEASED = 0x00040000U,
		BUTTON4_CLICKED = 0x00100000U,
		BUTTON4_DOUBLE_CLICKED = 0x00200000U,
		BUTTON4_TRIPLE_CLICKED = 0x00400000U,
		BUTTON_SHIFT = 0x02000000U,
		BUTTON_CTRL = 0x01000000U,
		BUTTON_ALT = 0x04000000U,
		ALL_MOUSE_EVENTS = 0x07ffffffU,
		REPORT_MOUSE_POSITION = 0x08000000U
	}
}
