// File generated by attrgen

namespace CursesSharp
{
	public static partial class Defs
	{
		public static int KEY_F(int n)
		{
			return KEY_F0 + n;
		}

        public static uint COLOR_PAIR(int n)
        {
            return NativeMethods.wrap_COLOR_PAIR(n);
        }

        public static short PAIR_NUMBER(uint n)
        {
            return NativeMethods.wrap_PAIR_NUMBER(n);
        }
    }
}
