/*
 * CursesSharp
 * 
 * Copyright 2009 Robert Konklewski
 * 
 * This library is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or (at your
 * option) any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Lesser General Public
 * License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * www.gnu.org/licenses/>.
 * 
 */

#ifdef HAVE_NCURSES_H
#include <ncurses.h>
#else
#include <curses.h>
#endif

#include <stdio.h>


#define GEN_ATTR(x) fprintf(OUT, "\t\tpublic const uint " #x " = 0x%.8lxU;\n", (x))
#define GEN_ACS(x) fprintf(OUT, "\t\tpublic const uint " #x " = 0x%.8lxU;\n", (x))
#define GEN_COLOR(x) fprintf(OUT, "\t\tpublic const short " #x " = 0x%x;\n", (x))
#define GEN_KEY(x) fprintf(OUT, "\t\tpublic const int " #x " = 0x%.3x;\n", (x))
#define GEN_MMASK(x) fprintf(OUT, "\t\tpublic const uint " #x " = 0x%.8lxU;\n", (x))

int main(int argc, char **argv)
{
	FILE* OUT;

	if (argc < 2)
		return -1;
	OUT = fopen(argv[1], "wt");
	if (!OUT)
		return -1;

#ifndef WIN32
	initscr();
#endif

	fprintf(OUT, "// File generated by attrgen\n");
	fprintf(OUT, "\n");

	fprintf(OUT, "namespace CursesSharp\n");
	fprintf(OUT, "{\n");

	fprintf(OUT, "\tpublic static partial class Defs\n");
	fprintf(OUT, "\t{\n");

	fprintf(OUT, "\t\t// Character attributes\n");
	GEN_ATTR(A_NORMAL);
	GEN_ATTR(A_STANDOUT);
	GEN_ATTR(A_UNDERLINE);
	GEN_ATTR(A_REVERSE);
	GEN_ATTR(A_BLINK);
	GEN_ATTR(A_DIM);
	GEN_ATTR(A_BOLD);
	GEN_ATTR(A_PROTECT);
	GEN_ATTR(A_INVIS);
	GEN_ATTR(A_ALTCHARSET);
	GEN_ATTR(A_CHARTEXT);

	fprintf(OUT, "\n");

	fprintf(OUT, "\t\t// Line drawing characters\n");
	GEN_ACS(ACS_BLOCK);
	GEN_ACS(ACS_BOARD);
	GEN_ACS(ACS_BTEE);
	GEN_ACS(ACS_BULLET);
	GEN_ACS(ACS_CKBOARD);
	GEN_ACS(ACS_DARROW);
	GEN_ACS(ACS_DEGREE);
	GEN_ACS(ACS_DIAMOND);
	GEN_ACS(ACS_GEQUAL);
	GEN_ACS(ACS_HLINE);
	GEN_ACS(ACS_LANTERN);
	GEN_ACS(ACS_LARROW);
	GEN_ACS(ACS_LEQUAL);
	GEN_ACS(ACS_LLCORNER);
	GEN_ACS(ACS_LRCORNER);
	GEN_ACS(ACS_LTEE);
	GEN_ACS(ACS_NEQUAL);
	GEN_ACS(ACS_PI);
	GEN_ACS(ACS_PLMINUS);
	GEN_ACS(ACS_PLUS);
	GEN_ACS(ACS_RARROW);
	GEN_ACS(ACS_RTEE);
	GEN_ACS(ACS_S1);
	GEN_ACS(ACS_S3);
	GEN_ACS(ACS_S7);
	GEN_ACS(ACS_S9);
	GEN_ACS(ACS_STERLING);
	GEN_ACS(ACS_TTEE);
	GEN_ACS(ACS_UARROW);
	GEN_ACS(ACS_ULCORNER);
	GEN_ACS(ACS_URCORNER);
	GEN_ACS(ACS_VLINE);
	
	fprintf(OUT, "\n");

	fprintf(OUT, "\t\t// Colors\n");
	GEN_COLOR(COLOR_BLACK);
	GEN_COLOR(COLOR_RED);
	GEN_COLOR(COLOR_GREEN);
	GEN_COLOR(COLOR_BLUE);
	GEN_COLOR(COLOR_CYAN);
	GEN_COLOR(COLOR_MAGENTA);
	GEN_COLOR(COLOR_YELLOW);
	GEN_COLOR(COLOR_WHITE);

	fprintf(OUT, "\n");

	fprintf(OUT, "\t\t// Keys\n");
	GEN_KEY(KEY_BREAK);
	GEN_KEY(KEY_DOWN);
	GEN_KEY(KEY_UP);
	GEN_KEY(KEY_LEFT);
	GEN_KEY(KEY_RIGHT);
	GEN_KEY(KEY_HOME);
	GEN_KEY(KEY_BACKSPACE);
	GEN_KEY(KEY_F0);
	GEN_KEY(KEY_DL);
	GEN_KEY(KEY_IL);
	GEN_KEY(KEY_DC);
	GEN_KEY(KEY_IC);
	GEN_KEY(KEY_EIC);
	GEN_KEY(KEY_CLEAR);
	GEN_KEY(KEY_EOS);
	GEN_KEY(KEY_EOL);
	GEN_KEY(KEY_SF);
	GEN_KEY(KEY_SR);
	GEN_KEY(KEY_NPAGE);
	GEN_KEY(KEY_PPAGE);
	GEN_KEY(KEY_STAB);
	GEN_KEY(KEY_CTAB);
	GEN_KEY(KEY_CATAB);
	GEN_KEY(KEY_ENTER);
	GEN_KEY(KEY_SRESET);
	GEN_KEY(KEY_RESET);
	GEN_KEY(KEY_PRINT);
	GEN_KEY(KEY_LL);
	GEN_KEY(KEY_A1);
	GEN_KEY(KEY_A3);
	GEN_KEY(KEY_B2);
	GEN_KEY(KEY_C1);
	GEN_KEY(KEY_C3);
	GEN_KEY(KEY_BTAB);
	GEN_KEY(KEY_BEG);
	GEN_KEY(KEY_CANCEL);
	GEN_KEY(KEY_CLOSE);
	GEN_KEY(KEY_COMMAND);
	GEN_KEY(KEY_COPY);
	GEN_KEY(KEY_CREATE);
	GEN_KEY(KEY_END);
	GEN_KEY(KEY_EXIT);
	GEN_KEY(KEY_FIND);
	GEN_KEY(KEY_HELP);
	GEN_KEY(KEY_MARK);
	GEN_KEY(KEY_MESSAGE);
	GEN_KEY(KEY_MOUSE);
	GEN_KEY(KEY_MOVE);
	GEN_KEY(KEY_NEXT);
	GEN_KEY(KEY_OPEN);
	GEN_KEY(KEY_OPTIONS);
	GEN_KEY(KEY_PREVIOUS);
	GEN_KEY(KEY_REDO);
	GEN_KEY(KEY_REFERENCE);
	GEN_KEY(KEY_REFRESH);
	GEN_KEY(KEY_REPLACE);
	GEN_KEY(KEY_RESIZE);
	GEN_KEY(KEY_RESTART);
	GEN_KEY(KEY_RESUME);
	GEN_KEY(KEY_SAVE);
	GEN_KEY(KEY_SBEG);
	GEN_KEY(KEY_SCANCEL);
	GEN_KEY(KEY_SCOMMAND);
	GEN_KEY(KEY_SCOPY);
	GEN_KEY(KEY_SCREATE);
	GEN_KEY(KEY_SDC);
	GEN_KEY(KEY_SDL);
	GEN_KEY(KEY_SELECT);
	GEN_KEY(KEY_SEND);
	GEN_KEY(KEY_SEOL);
	GEN_KEY(KEY_SEXIT);
	GEN_KEY(KEY_SFIND);
	GEN_KEY(KEY_SHELP);
	GEN_KEY(KEY_SHOME);
	GEN_KEY(KEY_SIC);
	GEN_KEY(KEY_SLEFT);
	GEN_KEY(KEY_SMESSAGE);
	GEN_KEY(KEY_SMOVE);
	GEN_KEY(KEY_SNEXT);
	GEN_KEY(KEY_SOPTIONS);
	GEN_KEY(KEY_SPREVIOUS);
	GEN_KEY(KEY_SPRINT);
	GEN_KEY(KEY_SREDO);
	GEN_KEY(KEY_SREPLACE);
	GEN_KEY(KEY_SRIGHT);
	GEN_KEY(KEY_SRSUME);
	GEN_KEY(KEY_SSAVE);
	GEN_KEY(KEY_SSUSPEND);
	GEN_KEY(KEY_SUNDO);
	GEN_KEY(KEY_SUSPEND);
	GEN_KEY(KEY_UNDO);

	fprintf(OUT, "\n");

	fprintf(OUT, "\t\tpublic static int KEY_F(int n)\n");
	fprintf(OUT, "\t\t{\n");
	fprintf(OUT, "\t\t\treturn KEY_F0 + n;\n");
	fprintf(OUT, "\t\t}\n");

	fprintf(OUT, "\n");

	fprintf(OUT, "\t\t// Mouse event masks\n");
	GEN_MMASK(BUTTON1_PRESSED);
	GEN_MMASK(BUTTON1_RELEASED);
	GEN_MMASK(BUTTON1_CLICKED);
	GEN_MMASK(BUTTON1_DOUBLE_CLICKED);
	GEN_MMASK(BUTTON1_TRIPLE_CLICKED);
	GEN_MMASK(BUTTON2_PRESSED);
	GEN_MMASK(BUTTON2_RELEASED);
	GEN_MMASK(BUTTON2_CLICKED);
	GEN_MMASK(BUTTON2_DOUBLE_CLICKED);
	GEN_MMASK(BUTTON2_TRIPLE_CLICKED);
	GEN_MMASK(BUTTON3_PRESSED);
	GEN_MMASK(BUTTON3_RELEASED);
	GEN_MMASK(BUTTON3_CLICKED);
	GEN_MMASK(BUTTON3_DOUBLE_CLICKED);
	GEN_MMASK(BUTTON3_TRIPLE_CLICKED);
	GEN_MMASK(BUTTON_SHIFT);
	GEN_MMASK(BUTTON_CTRL);
	GEN_MMASK(BUTTON_ALT);
	GEN_MMASK(ALL_MOUSE_EVENTS);
	GEN_MMASK(REPORT_MOUSE_POSITION);

	fprintf(OUT, "\t}\n");

	fprintf(OUT, "}\n");

#ifndef WIN32
	endwin();
#endif

	fclose(OUT);

	return 0;
}
